### ISSUE TITLE
<a> and <iframe> HTML tags are both broken due to corresponding SVG tags

### ISSUE THREAD

**Issue by natorojr** [queckezz/elementx#9]
The following code renders a blank screen (built with Webpack and running in the browser):

```js
const { a, iframe } = require('elementx');

addEventListener('DOMContentLoaded', main);

function main() {
  document.body.appendChild(a({ href: 'http://www.google.com' }, 'Text'));
  document.body.appendChild(iframe({ href: 'http://www.google.com', width: '500px', height: '500px;' }));
}
```

Based on my cursory investigation, I believe the reason is because `a` and `iframe` are tags that exist in both [html-tag-names](https://github.com/wooorm/html-tag-names/blob/master/index.json) and [svg-tag-names](https://github.com/wooorm/svg-tag-names/blob/master/index.json).

For tags that exists in both sets (HTML and SVG), it seems like the code is giving preference to the creation of an SVG element ([refer to this line of code](https://github.com/queckezz/elementx/blob/a7081838ea946578318fa36f3da35489301e94f2/index.js#L44)), which causes a number of issues for those of us that are rendering HTML.

If we switch the logic/order of that ternary such that the HTML element is created (instead of the SVG one), I have confirmed that everything starts rendering properly.

PR to follow.

**Comment by queckezz** [comment]
Closed via #10
